<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Page extends Model
{
    //
    public function save(array $options = [])
    {
        cache()->forget('pages');
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
